### ISSUE TITLE
Windows Support?

### ISSUE THREAD

**Issue by xXFreeFunXx** [n0la/rcon#22]
Hi,
would also be a Windows version possible?
best regards
FreeFun

**Comment by n0la** [comment]
You should be able to compile `rcon` with msys2 without too many issues.

**Comment by xXFreeFunXx** [comment]
> You should be able to compile `rcon` with msys2 without too many issues.

I have no idea about compiling

**Comment by butaford** [comment]
Without official support !!!
[rcon_msys2.zip](https://github.com/n0la/rcon/files/6421330/rcon_msys2.zip)
1. Extract archive, example d:\programs\rcon
2. Add to User variables PATH
![image](https://user-images.githubusercontent.com/5542160/117010792-d4145780-acf5-11eb-9fb1-fc1578f81e32.png)
3. Open d:\programs\rconrc.conf and add server
4. Open cmd and run command: rcon test status
![image](https://user-images.githubusercontent.com/5542160/117011306-60267f00-acf6-11eb-891a-254268410a91.png)

P.S. Since msys2 does not support libbsd, I had to apply a patch from Entware
https://github.com/Entware/rtndev/blob/master/rcon/patches/010-remove_libbsd_dep.patch

P.S. English is not my native language, so please be kind to my mistakes.

**Comment by butaford** [comment]
Build from original source code. Not patched
Cygwin:
[rcon_cygwin.zip](https://github.com/n0la/rcon/files/6422930/rcon_cygwin.zip)

**Comment by n0la** [comment]
Thanks @butaford for the windows builds.
